theme = "initio"
title = "Mary Phuong"

[params]
    name = "Mary Phuong"
    description = "Machine Learning PhD at IST Austria"
    email = "bphuong-at-ist-dot-ac-dot-at"
    year = 2019
    avatar = "photo1.jpg"

    